version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src/:/src/
    env_file:
      ./.env
    ports:
      - 8000:8000
    restart: always
