name: api-email

on: [pull_request, push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build-project
      run: |
        make build
    - uses: actions/tests
    - name: test
      run: |
        make test
