name: api-email

on: [pull_request, push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run:
        make build

    - name: install-requirements
      run:
        make install-requirements

    - name: Tests
      run:
        make test
